#!/usr/bin/env node
/**
 * Writes the blog.
 *
 * Posts are generated by Claude from a list of topics, then rendered into the same
 * shell as the rest of the site — one HTML file each, plus an index and an RSS feed.
 * Static output on purpose: the site is a static host, and a post that needs a server
 * to render is a post that disappears when the server has a bad day.
 *
 * A topic already written is skipped, so this is safe to re-run. Delete a post's file
 * to have it written again.
 *
 *   ANTHROPIC_API_KEY=... node generate-blog.mjs          # write anything missing
 *   ANTHROPIC_API_KEY=... node generate-blog.mjs --one    # write a single post
 */
import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const BLOG = join(HERE, 'blog');
const MODEL = 'claude-sonnet-5';

/* Topics a Shopify merchant actually searches for, each tied to something the app does.
   Add to the end; the slug is what marks a post as written, so never renumber. */
const TOPICS = [
  ['how-to-organize-a-shopify-warehouse', 'How to organise a small Shopify warehouse', 'Somebody with a spare room or a unit, boxes on the floor, and no system. What to name shelves, how granular to go, and when bins start paying off.'],
  ['bin-naming-conventions', 'Bin naming that still makes sense at 400 bins', 'Aisle-rack-shelf schemes, why sequential numbers fall apart, and how to leave room to grow.'],
  ['pick-list-mistakes', 'Five things that slow down picking', 'Walking order, one product in several bins, no barcode, batching, and printing the list too late.'],
  ['cycle-counting-small-warehouse', 'Cycle counting without closing for a day', 'Counting a few bins a week instead of everything at once, which bins to start with, and what to do with the differences.'],
  ['shopify-inventory-locations-vs-bins', 'Shopify locations are not bins', 'What Shopify tracks, what it does not, and why quantity without position is only half an inventory.'],
  ['receiving-a-pallet', 'Receiving a pallet without losing an afternoon', 'Scanning into a bin as you unload, when to label, and why the fast path is one bin at a time.'],
  ['dead-stock', 'Finding the stock that is not moving', 'How dead stock hides in a warehouse, what 90 days of no movement really costs, and what to do about it.'],
  ['warehouse-staff-access', 'What your warehouse staff should not see', 'Costs, margins and payouts on a shared tablet, and how to give someone the picking screen and nothing else.'],
];

/* The photo bank lives in blog-photos.json — 51 warehouse photos, no app screenshots:
   this blog is read by people who have not installed anything yet. Four came from the
   binsusa.com blog (Unsplash); the rest from Wikimedia Commons, and almost all of those
   are CC BY or CC BY-SA, which is why every hero renders a credit line. Assignment is by
   topic index, so the eight topics that exist today keep the photo picked for their
   subject and topic 9 onward never repeats a photo until the 51st post. TOPICS is
   append-only for exactly this reason — renumbering it reshuffles every published hero. */
const PHOTOS = JSON.parse(readFileSync(join(HERE, 'blog-photos.json'), 'utf8'));
const photoFor = (i) => PHOTOS[i % PHOTOS.length];

const esc = (t) => String(t).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

function credit(ph) {
  if (!ph.source) return `Photo: ${esc(ph.credit)}`;
  return `Photo: <a href="${esc(ph.source)}" rel="nofollow noopener" style="color:inherit">`
       + `${esc(ph.credit)}</a> · ${esc(ph.license)}`;
}

function figure(i) {
  const ph = photoFor(i);
  return `        <figure class="post-hero" style="margin:0 0 26px">
          <img src="/assets/blog/${ph.file}" alt="${esc(ph.alt)}" data-es-alt="${esc(ph.altEs)}"
               loading="lazy" decoding="async"
               style="width:100%;aspect-ratio:16/9;object-fit:cover;border-radius:12px;display:block" />
          <figcaption style="color:#94a3b8;font-size:11px;margin-top:6px">${credit(ph)}</figcaption>
        </figure>`;
}

function thumb(i) {
  const ph = photoFor(i);
  return `        <img src="/assets/blog/${ph.file}" alt="${esc(ph.alt)}" data-es-alt="${esc(ph.altEs)}" loading="lazy" decoding="async"
             style="width:100%;aspect-ratio:16/9;object-fit:cover;border-radius:10px;border:1px solid #e2e8f0;margin-bottom:14px;display:block" />`;
}

const SYSTEM = `You write for the Bins-USA blog. Bins-USA is a Shopify app that records WHERE each product is stored in a warehouse — a shelf, a box, a rack, called a bin.

Write for a Shopify merchant who runs a small or mid-size warehouse. They are practical, busy, and have heard enough marketing.

RULES
- Plain, concrete prose. No hype, no "in today's fast-paced world", no invented statistics, no fake case studies.
- Never invent a Bins-USA feature or price. You may mention what the app does — bins, scanning, pick lists, cycle counts, receiving, transfers, labels, reports, users and roles — but do not state prices.
- Most of the piece should be useful even to someone who never installs anything. Earn the reader first.
- Mention Bins-USA where it genuinely fits, once or twice, never in every section.
- 700-900 words. A short intro, then 3-5 sections with h2 headings, then a couple of closing lines.
- Output HTML fragments only: <p>, <h2>, <ul>, <li>, <strong>. No <html>, <head>, <body>, no markdown, no title (the title is supplied separately).`;

const SYSTEM_ES = `Traduces al español entradas del blog de Bins-USA, escritas para comerciantes de Shopify que manejan una bodega pequeña o mediana.

REGLAS
- Español neutro latinoamericano. Usted, no tú.
- Ortografía completa: todas las tildes, las eñes y los signos de apertura (¿ ¡).
- Conserva los términos que la app usa en inglés y que la gente de bodega dice así: bin, SKU, pick list se traduce como «lista de selección», picking como «selección».
- Conserva exactamente las etiquetas HTML que vengan dentro del texto (<strong>, <em>).
- No agregues, no quites y no resumas. Una línea de entrada, una línea de salida.
- No inventes funciones ni precios de Bins-USA.`;

/* One call per post: the blocks go in numbered, the Spanish comes back numbered, so a
   dropped or merged line is caught by the count instead of silently shifting the text. */
async function translate(blocks) {
  const numbered = blocks.map((b, i) => `${i + 1}. ${b}`).join('\n');
  const out = await ask({
    system: SYSTEM_ES, max_tokens: 4000,
    user: `Traduce cada línea numerada. Devuelve exactamente ${blocks.length} líneas, con el mismo número al inicio y nada más.\n\n${numbered}`,
  });
  const es = out.split('\n').map((l) => l.trim()).filter(Boolean)
    .map((l) => l.replace(/^\d+\.\s*/, ''));
  if (es.length !== blocks.length) throw new Error(`translate: ${blocks.length} in, ${es.length} out`);
  return es;
}


async function ask({ system, user, max_tokens }) {
  const key = process.env.ANTHROPIC_API_KEY;
  if (!key) throw new Error('ANTHROPIC_API_KEY is not set');
  const r = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: { 'content-type': 'application/json', 'x-api-key': key, 'anthropic-version': '2023-06-01' },
    body: JSON.stringify({ model: MODEL, max_tokens, system, messages: [{ role: 'user', content: user }] }),
  });
  if (!r.ok) throw new Error(`anthropic ${r.status}: ${(await r.text()).slice(0, 200)}`);
  const d = await r.json();
  return (d.content || []).filter((c) => c.type === 'text').map((c) => c.text).join('').trim();
}

async function write(title, brief) {
  return ask({ system: SYSTEM, max_tokens: 2500,
    user: `Title: ${title}\n\nWhat it should cover: ${brief}\n\nWrite the post body.` });
}

/* The shell comes from a real page, so the blog cannot drift from the site: change the
   nav or footer once and every post picks it up on the next run. */
function shell() {
  const src = readFileSync(join(HERE, 'features.html'), 'utf8');
  return {
    head: src.slice(0, src.indexOf('</head>') + 7),
    nav: src.slice(src.indexOf('  <!-- NAV -->'), src.indexOf('</nav>') + 6),
    foot: src.slice(src.indexOf('  <footer>'), src.indexOf('</footer>') + 9),
    script: src.slice(src.indexOf('  <!-- Language toggle.'), src.indexOf('</body>')),
  };
}

function render({ title, titleEs, body, date, slug, i }) {
  const s = shell();
  const head = s.head.replace(/<title>[^<]*<\/title>/, `<title data-es="${esc(titleEs)} — Bins-USA">${title} — Bins-USA</title>`);
  return `${head}<body>
  <a class="skip-link" href="#maincontent" data-es="Ir al contenido">Skip to content</a>

${s.nav}

  <main id="maincontent" tabindex="-1">
  <article class="section" style="max-width:760px;margin:0 auto">
    <p style="color:#64748b;font-size:13px;margin-bottom:6px">${date}</p>
    <h1 data-es="${esc(titleEs)}" style="font-size:32px;font-weight:800;line-height:1.25;margin-bottom:20px">${title}</h1>
${figure(i)}
    <div style="font-size:16px;line-height:1.75">
${body}
    </div>
    <p style="margin-top:32px"><a href="/blog/" data-es="← Todos los artículos">← All posts</a></p>
  </article>
  <section class="section" style="text-align:center;padding-top:0">
    <a href="https://apps.shopify.com/bins-usa" class="btn-plan basic" style="display:inline-block;padding:14px 28px;max-width:340px" data-es="🛍️ Instalar en Shopify — Es gratis →">🛍️ Install on Shopify — It's Free →</a>
  </section>
  </main>

${s.foot}
${s.script}
</body>
</html>
`;
}

function index(posts) {
  const s = shell();
  const head = s.head.replace(/<title>[^<]*<\/title>/, '<title>Blog — Bins-USA</title>');
  const items = posts.map((p) => `      <a class="feature-card" href="/blog/${p.slug}.html" style="text-decoration:none;color:inherit;display:block">
${thumb(p.i)}
        <p style="color:#64748b;font-size:12px;margin-bottom:6px">${p.date}</p>
        <h3${p.titleEs ? ` data-es="${esc(p.titleEs)}"` : ''}>${p.title}</h3>
        <p${p.briefEs ? ` data-es="${esc(p.briefEs)}"` : ''}>${p.brief}</p>
      </a>`).join('\n');
  return `${head}<body>
  <a class="skip-link" href="#maincontent" data-es="Ir al contenido">Skip to content</a>

${s.nav}

  <main id="maincontent" tabindex="-1">
  <section class="section">
    <div class="section-label" data-es="Blog">Blog</div>
    <h2 class="section-title" data-es="Ideas para organizar su bodega">Ideas for organising your warehouse</h2>
    <p class="section-subtitle" data-es="Cosas prácticas que sirven aunque nunca instale nada.">Practical things that are useful even if you never install anything.</p>
    <div class="features-grid" style="max-width:1040px;margin:0 auto">
${items}
    </div>
  </section>
  </main>

${s.foot}
${s.script}
</body>
</html>
`;
}

function feed(posts) {
  const items = posts.map((p) => `    <item>
      <title>${p.title.replace(/&/g, '&amp;')}</title>
      <link>https://bins-usa.com/blog/${p.slug}.html</link>
      <guid>https://bins-usa.com/blog/${p.slug}.html</guid>
      <description>${p.brief.replace(/&/g, '&amp;')}</description>
    </item>`).join('\n');
  return `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0"><channel>
  <title>Bins-USA Blog</title>
  <link>https://bins-usa.com/blog/</link>
  <description>Practical ideas for organising a Shopify warehouse.</description>
${items}
</channel></rss>
`;
}

const only = process.argv.includes('--one');
const today = new Date().toISOString().slice(0, 10);
let written = 0;
const briefs = {};

for (const [i, [slug, title, brief]] of TOPICS.entries()) {
  const file = join(BLOG, `${slug}.html`);
  if (existsSync(file)) { console.log(`  skip   ${slug}`); continue; }
  process.stdout.write(`  write  ${slug} … `);
  try {
    const body = await write(title, brief);
    const blocks = [...body.matchAll(/<(p|h2|h3|li)>([\s\S]*?)<\/\1>/g)];
    const es = await translate([title, brief, ...blocks.map((m) => m[2].trim())]);
    const [titleEs, briefEs, ...bodyEs] = es;
    let k = 0;
    const bodyBilingual = body.replace(/<(p|h2|h3|li)>([\s\S]*?)<\/\1>/g,
      (m, tag, inner) => `<${tag} data-es="${esc(bodyEs[k++])}">${inner}</${tag}>`);
    writeFileSync(file, render({ title, titleEs, body: bodyBilingual, date: today, slug, i }));
    briefs[slug] = briefEs;
    console.log(`${body.length} chars`);
    written += 1;
    if (only) break;
  } catch (e) {
    console.log(`FAILED: ${e.message}`);
    break;      // a rate limit or a bad key: stop rather than burn through the list
  }
}

function esOf(slug) {
  const f = join(BLOG, `${slug}.html`);
  if (!existsSync(f)) return null;
  const m = readFileSync(f, 'utf8').match(/<h1[^>]*data-es="([^"]*)"/);
  return m ? m[1].replace(/&quot;/g, '"').replace(/&amp;/g, '&') : null;
}

const have = TOPICS.map((t, i) => [t, i]).filter(([[slug]]) => existsSync(join(BLOG, `${slug}.html`)))
  .map(([[slug, title, brief], i]) => ({ slug, title, brief, date: today, i,
     titleEs: esOf(slug), briefEs: briefs[slug] || null }));
writeFileSync(join(BLOG, 'index.html'), index(have));
writeFileSync(join(BLOG, 'feed.xml'), feed(have));
console.log(`\n  ${written} written, ${have.length} posts on the index`);
