#!/usr/bin/env node
/**
 * Writes the blog.
 *
 * Posts are generated by Claude from a list of topics, then rendered into the same
 * shell as the rest of the site — one HTML file each, plus an index and an RSS feed.
 * Static output on purpose: the site is a static host, and a post that needs a server
 * to render is a post that disappears when the server has a bad day.
 *
 * A topic already written is skipped, so this is safe to re-run. Delete a post's file
 * to have it written again.
 *
 *   ANTHROPIC_API_KEY=... node generate-blog.mjs          # write anything missing
 *   ANTHROPIC_API_KEY=... node generate-blog.mjs --one    # write a single post
 */
import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const BLOG = join(HERE, 'blog');
const MODEL = 'claude-sonnet-5';

/* Topics a Shopify merchant actually searches for, each tied to something the app does.
   Add to the end; the slug is what marks a post as written, so never renumber. */
const TOPICS = [
  ['how-to-organize-a-shopify-warehouse', 'How to organise a small Shopify warehouse', 'Somebody with a spare room or a unit, boxes on the floor, and no system. What to name shelves, how granular to go, and when bins start paying off.'],
  ['bin-naming-conventions', 'Bin naming that still makes sense at 400 bins', 'Aisle-rack-shelf schemes, why sequential numbers fall apart, and how to leave room to grow.'],
  ['pick-list-mistakes', 'Five things that slow down picking', 'Walking order, one product in several bins, no barcode, batching, and printing the list too late.'],
  ['cycle-counting-small-warehouse', 'Cycle counting without closing for a day', 'Counting a few bins a week instead of everything at once, which bins to start with, and what to do with the differences.'],
  ['shopify-inventory-locations-vs-bins', 'Shopify locations are not bins', 'What Shopify tracks, what it does not, and why quantity without position is only half an inventory.'],
  ['receiving-a-pallet', 'Receiving a pallet without losing an afternoon', 'Scanning into a bin as you unload, when to label, and why the fast path is one bin at a time.'],
  ['dead-stock', 'Finding the stock that is not moving', 'How dead stock hides in a warehouse, what 90 days of no movement really costs, and what to do about it.'],
  ['warehouse-staff-access', 'What your warehouse staff should not see', 'Costs, margins and payouts on a shared tablet, and how to give someone the picking screen and nothing else.'],
];

/* Art from the binsusa.com gallery. The five screenshots are the WMS Cloud app, so their
   captions say so; the two banner designs exist in English and Spanish and swap with the
   site's language toggle. A slug that is not listed falls back to a banner, so a new topic
   is never published without an image. */
const CDN = 'https://cdn.shopify.com/s/files/1/0598/3312/2968/files';
const BANNERS = [
  [`${CDN}/banner-1_1.png?v=1780978103`, `${CDN}/bins-usa_1.png?v=1781926971`,
   'Bin-based inventory management.', 'Gestión de inventario basada en bins.'],
  [`${CDN}/banner-2_2.png?v=1780978103`, `${CDN}/bins-usa_2.png?v=1781926914`,
   'Scan it in once and the count is right.', 'Escanéalo una vez y la cuenta queda bien.'],
];
const IMAGES = {
  'bin-naming-conventions': [`${CDN}/SCREENSHOT-4.png?v=1780978150`, null,
    'Inventory value grouped by bin — the names carry the location: BIN 200, BIN 160, BIN 089.',
    'Valor de inventario por bin — el nombre lleva la ubicación: BIN 200, BIN 160, BIN 089.'],
  'cycle-counting-small-warehouse': [`${CDN}/SCREENSHOT-3_1.png?v=1780978150`, null,
    'Stock and bins side by side: what to count, and where it sits.',
    'Stock y bins uno al lado del otro: qué contar y dónde está.'],
  'dead-stock': [`${CDN}/SCREENSHOT-1_1.png?v=1780978150`, null,
    'The operations dashboard: what moved, what did not, and what needs attention.',
    'El panel de operaciones: qué se movió, qué no, y qué necesita atención.'],
  'how-to-organize-a-shopify-warehouse': BANNERS[0],
  'pick-list-mistakes': [`${CDN}/SCREENSHOT-2_1.png?v=1780978150`, null,
    'Pick lists grouped by order, with the pick status on every line.',
    'Listas de selección por orden, con el estado de selección en cada línea.'],
  'receiving-a-pallet': BANNERS[1],
  'shopify-inventory-locations-vs-bins': [`${CDN}/SCREENSHOT-3_1.png?v=1780978150`, null,
    'One product, several bins, inside a single Shopify location.',
    'Un producto, varios bins, dentro de una sola ubicación de Shopify.'],
  'warehouse-staff-access': [`${CDN}/SCREENSHOT-5.png?v=1780978150`, null,
    'Purchase order history — cost and spend, the numbers the floor does not need.',
    'Historial de órdenes de compra — costo y gasto, los números que la bodega no necesita.'],
};
function artFor(slug, i) { return IMAGES[slug] || BANNERS[i % BANNERS.length]; }
function esSrc(es) { return es ? ` data-es-src="${es}"` : ''; }

function figure(slug, i) {
  const [src, es, cap, capEs] = artFor(slug, i);
  return `        <figure class="post-hero" style="margin:0 0 26px">
          <img src="${src}"${esSrc(es)} alt="" loading="lazy" decoding="async"
               style="width:100%;height:auto;border-radius:12px;border:1px solid #e2e8f0;display:block" />
          <figcaption data-es="${capEs}" style="color:#64748b;font-size:13px;margin-top:8px;line-height:1.5">${cap}</figcaption>
        </figure>`;
}

function thumb(slug, i) {
  const [src, es] = artFor(slug, i);
  return `        <img src="${src}"${esSrc(es)} alt="" loading="lazy" decoding="async"
             style="width:100%;aspect-ratio:16/9;object-fit:cover;border-radius:10px;border:1px solid #e2e8f0;margin-bottom:14px;display:block" />`;
}

const SYSTEM = `You write for the Bins-USA blog. Bins-USA is a Shopify app that records WHERE each product is stored in a warehouse — a shelf, a box, a rack, called a bin.

Write for a Shopify merchant who runs a small or mid-size warehouse. They are practical, busy, and have heard enough marketing.

RULES
- Plain, concrete prose. No hype, no "in today's fast-paced world", no invented statistics, no fake case studies.
- Never invent a Bins-USA feature or price. You may mention what the app does — bins, scanning, pick lists, cycle counts, receiving, transfers, labels, reports, users and roles — but do not state prices.
- Most of the piece should be useful even to someone who never installs anything. Earn the reader first.
- Mention Bins-USA where it genuinely fits, once or twice, never in every section.
- 700-900 words. A short intro, then 3-5 sections with h2 headings, then a couple of closing lines.
- Output HTML fragments only: <p>, <h2>, <ul>, <li>, <strong>. No <html>, <head>, <body>, no markdown, no title (the title is supplied separately).`;

async function write(title, brief) {
  const key = process.env.ANTHROPIC_API_KEY;
  if (!key) throw new Error('ANTHROPIC_API_KEY is not set');
  const r = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: { 'content-type': 'application/json', 'x-api-key': key, 'anthropic-version': '2023-06-01' },
    body: JSON.stringify({
      model: MODEL, max_tokens: 2500, system: SYSTEM,
      messages: [{ role: 'user', content: `Title: ${title}\n\nWhat it should cover: ${brief}\n\nWrite the post body.` }],
    }),
  });
  if (!r.ok) throw new Error(`anthropic ${r.status}: ${(await r.text()).slice(0, 200)}`);
  const d = await r.json();
  return (d.content || []).filter((c) => c.type === 'text').map((c) => c.text).join('').trim();
}

/* The shell comes from a real page, so the blog cannot drift from the site: change the
   nav or footer once and every post picks it up on the next run. */
function shell() {
  const src = readFileSync(join(HERE, 'features.html'), 'utf8');
  return {
    head: src.slice(0, src.indexOf('</head>') + 7),
    nav: src.slice(src.indexOf('  <!-- NAV -->'), src.indexOf('</nav>') + 6),
    foot: src.slice(src.indexOf('  <footer>'), src.indexOf('</footer>') + 9),
    script: src.slice(src.indexOf('  <!-- Language toggle.'), src.indexOf('</body>')),
  };
}

function render({ title, body, date, slug, i }) {
  const s = shell();
  const head = s.head.replace(/<title>[^<]*<\/title>/, `<title>${title} — Bins-USA</title>`);
  return `${head}<body>
  <a class="skip-link" href="#maincontent" data-es="Ir al contenido">Skip to content</a>

${s.nav}

  <main id="maincontent" tabindex="-1">
  <article class="section" style="max-width:760px;margin:0 auto">
    <p style="color:#64748b;font-size:13px;margin-bottom:6px">${date}</p>
    <h1 style="font-size:32px;font-weight:800;line-height:1.25;margin-bottom:20px">${title}</h1>
${figure(slug, i)}
    <div style="font-size:16px;line-height:1.75">
${body}
    </div>
    <p style="margin-top:32px"><a href="/blog/" data-es="← Todos los artículos">← All posts</a></p>
  </article>
  <section class="section" style="text-align:center;padding-top:0">
    <a href="https://apps.shopify.com/bins-usa" class="btn-plan basic" style="display:inline-block;padding:14px 28px;max-width:340px" data-es="🛍️ Instalar en Shopify — Es gratis →">🛍️ Install on Shopify — It's Free →</a>
  </section>
  </main>

${s.foot}
${s.script}
</body>
</html>
`;
}

function index(posts) {
  const s = shell();
  const head = s.head.replace(/<title>[^<]*<\/title>/, '<title>Blog — Bins-USA</title>');
  const items = posts.map((p) => `      <a class="feature-card" href="/blog/${p.slug}.html" style="text-decoration:none;color:inherit;display:block">
${thumb(p.slug, p.i)}
        <p style="color:#64748b;font-size:12px;margin-bottom:6px">${p.date}</p>
        <h3>${p.title}</h3>
        <p>${p.brief}</p>
      </a>`).join('\n');
  return `${head}<body>
  <a class="skip-link" href="#maincontent" data-es="Ir al contenido">Skip to content</a>

${s.nav}

  <main id="maincontent" tabindex="-1">
  <section class="section">
    <div class="section-label" data-es="Blog">Blog</div>
    <h2 class="section-title" data-es="Ideas para organizar su bodega">Ideas for organising your warehouse</h2>
    <p class="section-subtitle" data-es="Cosas prácticas que sirven aunque nunca instale nada.">Practical things that are useful even if you never install anything.</p>
    <div class="features-grid" style="max-width:1040px;margin:0 auto">
${items}
    </div>
  </section>
  </main>

${s.foot}
${s.script}
</body>
</html>
`;
}

function feed(posts) {
  const items = posts.map((p) => `    <item>
      <title>${p.title.replace(/&/g, '&amp;')}</title>
      <link>https://bins-usa.com/blog/${p.slug}.html</link>
      <guid>https://bins-usa.com/blog/${p.slug}.html</guid>
      <description>${p.brief.replace(/&/g, '&amp;')}</description>
    </item>`).join('\n');
  return `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0"><channel>
  <title>Bins-USA Blog</title>
  <link>https://bins-usa.com/blog/</link>
  <description>Practical ideas for organising a Shopify warehouse.</description>
${items}
</channel></rss>
`;
}

const only = process.argv.includes('--one');
const today = new Date().toISOString().slice(0, 10);
let written = 0;

for (const [i, [slug, title, brief]] of TOPICS.entries()) {
  const file = join(BLOG, `${slug}.html`);
  if (existsSync(file)) { console.log(`  skip   ${slug}`); continue; }
  process.stdout.write(`  write  ${slug} … `);
  try {
    const body = await write(title, brief);
    writeFileSync(file, render({ title, body, date: today, slug, i }));
    console.log(`${body.length} chars`);
    written += 1;
    if (only) break;
  } catch (e) {
    console.log(`FAILED: ${e.message}`);
    break;      // a rate limit or a bad key: stop rather than burn through the list
  }
}

const have = TOPICS.map((t, i) => [t, i]).filter(([[slug]]) => existsSync(join(BLOG, `${slug}.html`)))
  .map(([[slug, title, brief], i]) => ({ slug, title, brief, date: today, i }));
writeFileSync(join(BLOG, 'index.html'), index(have));
writeFileSync(join(BLOG, 'feed.xml'), feed(have));
console.log(`\n  ${written} written, ${have.length} posts on the index`);
